### PR TITLE
Fix various source comment typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3`

### CODE REVIEW

**Comment by dprojects** [comment]
Typos are annoying. I am not native English speaker and I make a lot of this kind of mistakes, unfortunately. I read it but don't see it ;-) this is magic, I guess ;-) I am not into accepting pull requests because I need to test code each time before commit. Macros should be corrected in their repositories as well. I also was thinking if this is worth to add macros code to the woodworking workbench if there is auto-update menu option but maybe not all FreeCAD installations have urllib. Someday, when there is an opportunity, I will correct all typos. I will try to check each time the typos by the tool. Thanks.

**Comment by luzpaz** [comment]
These are non-breaking changes. Not sure what you need to test exactly... but ok

**Comment by dprojects** [comment]
Yes, looks OK. But sometimes even white space or tab may not work. However, I am sure it is fine but need to test always to be sure what I commit.

**Comment by dprojects** [comment]
I added typos checking to the dev-tool I use all the time for each commit: https://github.com/dprojects/dev-tools

**Pull request closed without merging**
