### PR TITLE
Update package.xml

### PR DESCRIPTION
**Pull request by Syres916**
Fixes https://github.com/dprojects/Woodworking/issues/36 and https://github.com/FreeCAD/FreeCAD/issues/11737

### CODE REVIEW

**Comment by Syres916** [comment]
Polite question, is there something the you don't approve of with this PR, the quicker it gets updated the quicker the users will get a reduction in warnings and have a Readme displaying correctly?

**Comment by kwgagel** [comment]
I'm seeing this issue as well. Is there an ETA on when it will be fixed?

**Comment by Anthony-Gaudino** [comment]
I can't find Woodworking on addon manager.
Is this issue also caused by this typo or does it only breaks the loading of the Readme?

**Comment by dprojects** [comment]
done

**Pull request closed without merging**
